# Generated by Django 3.2.4 on 2021-06-26 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tourapp.group'),
        ),
        migrations.AddField(
            model_name='group',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tourapp.user'),
        ),
        migrations.AddField(
            model_name='group_member',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tourapp.group'),
        ),
    ]
