# Generated by Django 3.2.4 on 2021-06-30 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
                ('number_in_group', models.IntegerField()),
                ('trip_start_date', models.DateTimeField()),
                ('trip_end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Group_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_first_name', models.CharField(max_length=50)),
                ('member_last_name', models.CharField(max_length=50)),
                ('member_health_restriction', models.BooleanField()),
                ('member_under_eighteen', models.BooleanField()),
                ('member_email', models.CharField(max_length=50)),
                ('member_phone_number', models.CharField(max_length=50)),
                ('group', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='bookings.group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='bookings.user'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_start_date_time', models.DateTimeField()),
                ('booking_end_date_time', models.DateTimeField()),
                ('booking_cost_local_currency', models.IntegerField()),
                ('booking_local_currency_type', models.CharField(max_length=50)),
                ('booking_location', models.CharField(max_length=500)),
                ('booking_phone_number', models.CharField(max_length=50)),
                ('booking_email_address', models.CharField(max_length=50)),
                ('booking_contact_name', models.CharField(max_length=50)),
                ('booking_contact_position', models.CharField(max_length=50)),
                ('booking_website', models.CharField(max_length=500)),
                ('booking_description', models.CharField(max_length=500)),
                ('booking_group', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='bookings.group')),
            ],
        ),
    ]
